version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: autotest_api
    ports:
      - "5033:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  web:
    build:
      context: ./AutoTestWeb
      dockerfile: Dockerfile
    container_name: autotest_web
    ports:
      - "80:80"
    depends_on:
      - api
    restart: always